### ISSUE TITLE
Duplicating Trucks

### ISSUE THREAD

**Issue by soolaimon** [soolaimon/mobile_noms#2]
Since most of the time a users trucks will be the same (same photo, food type, description, etc) we'll want to make it easy for them to add a new truck with all of that same info instead of having to redo the same info for each truck.

This actually might be where our "ruby logic" requirement comes in. But maybe not.

**Comment by Rubiromi** [comment]
Can we make it render to their existing truck editing page, and somehow create a button for "Save as different truck" instead of "update"?

**Comment by soolaimon** [comment]
Probably. That might be the way to go as it will let them make changes before they save it.

What I was thinking was something similar what we did on our dental schedule app where you click a button and it just automatically created a new appointment in six months. Which do you think is best? (everyone)

**Comment by Rubiromi** [comment]
You know how _form has placeholders like "please enter your name", or "please enter your location".  Can we leave their existing truck information as placeholders like the editing page do, so they can only change the parts they have to?

**Comment by soolaimon** [comment]
Yep! They wouldn't be placeholders though. They would be values (that's what the edit form has). Placeholders are just for show. If you submit a form, it doesn't count the placeholders as data.
