### ISSUE TITLE
truck show page is not working

### ISSUE THREAD

**Issue by Rubiromi** [soolaimon/mobile_noms#5]
# truck-map data-truck="#{@truck.id}" data-location="#{@truck.location.id}"

is giving us an error and show page is not working

**Comment by soolaimon** [comment]
I'm not getting an error. What's the error message?

**Comment by soolaimon** [comment]
It might have to do with your DB being different than mine. I had to make some changes to the seed file to work right with the associations and stuff as I was doing geolocation. I'm still trying to get everything together, but I'll work on getting everyone database compatible so we can all see the show page.

**Comment by soolaimon** [comment]
Ok it should be fine now. To get it working you'll need to:
pull down develop
rake db:drop
rake db:migrate
Create an account for yourself (the trucks (and in turn the locations) in the seedfile are set up to belong to the user with id of 1, that way we can all log in and we have those truck in there belonging to us)
rake db:seed

Sorry about that.

**Comment by Rubiromi** [comment]
Got it. Thanks.
