### ISSUE TITLE
users phone number is not saved

### ISSUE THREAD

**Issue by Rubiromi** [soolaimon/mobile_noms#7]
on user/edit page, user's phone number doesn't show.  I checked it on rails console. It looks like phone number is not saved.

**Comment by tysonvanburen** [comment]
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).concat([ :first_name, :last_name, :phone ])
    _devise_parameter_sanitizer.for(:account_update).concat([ :first_name, :last_name, :phone])_
  end
end

It wasn't giving permission to save phone number  on edit page.
